
import type { WordCard, CardCategory, SentencePattern } from '@/types';
import { nanoid } from 'nanoid';

export const GRID_ROWS = 5;
export const GRID_COLS = 8;
export const INITIAL_HAND_SIZE = 14;
export const PLAYER_COUNT = 2;

export const CATEGORIES: CardCategory[] = [
  'Noun', 'Verb', 'Adjective', 'Adverb', 'Pronoun', 
  'Article', 'Preposition', 'Conjunction'
];

export const CARD_COLORS: Record<CardCategory, string> = {
  Noun: 'noun-gradient',
  Verb: 'verb-gradient',
  Adjective: 'adjective-gradient',
  Adverb: 'adverb-gradient',
  Pronoun: 'pronoun-gradient',
  Article: 'article-gradient',
  Preposition: 'preposition-gradient',
  Conjunction: 'conjunction-gradient',
  Unknown: 'default-gradient',
};

export const INITIAL_DECK: WordCard[] = [
  // Nouns (Existing + some new for variety + longer words)
  { id: nanoid(), text: 'Apple', categories: ['Noun'] }, { id: nanoid(), text: 'Ant', categories: ['Noun'] },
  { id: nanoid(), text: 'Art', categories: ['Noun'] }, { id: nanoid(), text: 'Actor', categories: ['Noun'] },
  { id: nanoid(), text: 'Act', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Adventure', categories: ['Noun'] },
  { id: nanoid(), text: 'Algorithm', categories: ['Noun'] }, { id: nanoid(), text: 'Automobile', categories: ['Noun'] },
  { id: nanoid(), text: 'Architecture', categories: ['Noun'] },
  { id: nanoid(), text: 'Ball', categories: ['Noun'] }, { id: nanoid(), text: 'Book', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Bear', categories: ['Noun'] }, { id: nanoid(), text: 'Boat', categories: ['Noun'] },
  { id: nanoid(), text: 'Box', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Bread', categories: ['Noun'] },
  { id: nanoid(), text: 'Boy', categories: ['Noun'] }, { id: nanoid(), text: 'Girl', categories: ['Noun'] },
  { id: nanoid(), text: 'Bicycle', categories: ['Noun'] }, { id: nanoid(), text: 'Butterfly', categories: ['Noun'] },
  { id: nanoid(), text: 'Banana', categories: ['Noun'] }, { id: nanoid(), text: 'Building', categories: ['Noun'] },
  { id: nanoid(), text: 'Cat', categories: ['Noun'] }, { id: nanoid(), text: 'Car', categories: ['Noun'] },
  { id: nanoid(), text: 'Cake', categories: ['Noun'] }, { id: nanoid(), text: 'Cloud', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Chair', categories: ['Noun'] }, { id: nanoid(), text: 'City', categories: ['Noun'] },
  { id: nanoid(), text: 'Child', categories: ['Noun'] }, { id: nanoid(), text: 'Country', categories: ['Noun'] },
  { id: nanoid(), text: 'Call', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Change', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Cook', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Computer', categories: ['Noun'] },
  { id: nanoid(), text: 'Chocolate', categories: ['Noun'] }, { id: nanoid(), text: 'Conversation', categories: ['Noun'] },
  { id: nanoid(), text: 'Challenge', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Dog', categories: ['Noun'] }, { id: nanoid(), text: 'Door', categories: ['Noun'] },
  { id: nanoid(), text: 'Dream', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Desk', categories: ['Noun'] },
  { id: nanoid(), text: 'Day', categories: ['Noun'] }, { id: nanoid(), text: 'Duck', categories: ['Noun'] },
  { id: nanoid(), text: 'Doctor', categories: ['Noun'] }, { id: nanoid(), text: 'Dinner', categories: ['Noun'] },
  { id: nanoid(), text: 'Dance', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Drink', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Drive', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Dinosaur', categories: ['Noun'] },
  { id: nanoid(), text: 'Discovery', categories: ['Noun'] }, { id: nanoid(), text: 'Diamond', categories: ['Noun'] },
  { id: nanoid(), text: 'Development', categories: ['Noun'] },
  { id: nanoid(), text: 'Egg', categories: ['Noun'] }, { id: nanoid(), text: 'Earth', categories: ['Noun'] },
  { id: nanoid(), text: 'Elephant', categories: ['Noun'] }, { id: nanoid(), text: 'Eye', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Ear', categories: ['Noun'] }, { id: nanoid(), text: 'End', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Energy', categories: ['Noun'] }, { id: nanoid(), text: 'Engine', categories: ['Noun'] },
  { id: nanoid(), text: 'Environment', categories: ['Noun'] }, { id: nanoid(), text: 'Experience', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Fish', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Flower', categories: ['Noun'] },
  { id: nanoid(), text: 'Friend', categories: ['Noun'] }, { id: nanoid(), text: 'Fire', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Forest', categories: ['Noun'] }, { id: nanoid(), text: 'Farm', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Food', categories: ['Noun'] }, { id: nanoid(), text: 'Family', categories: ['Noun'] },
  { id: nanoid(), text: 'Fly', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Future', categories: ['Noun'] },
  { id: nanoid(), text: 'Freedom', categories: ['Noun'] }, { id: nanoid(), text: 'Festival', categories: ['Noun'] },
  { id: nanoid(), text: 'Furniture', categories: ['Noun'] },
  { id: nanoid(), text: 'Game', categories: ['Noun'] }, { id: nanoid(), text: 'Goat', categories: ['Noun'] },
  { id: nanoid(), text: 'Glass', categories: ['Noun'] }, { id: nanoid(), text: 'Garden', categories: ['Noun'] },
  { id: nanoid(), text: 'Ghost', categories: ['Noun'] }, { id: nanoid(), text: 'Gift', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Gold', categories: ['Noun', 'Adjective'] }, { id: nanoid(), text: 'Ground', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Government', categories: ['Noun'] }, { id: nanoid(), text: 'Galaxy', categories: ['Noun'] },
  { id: nanoid(), text: 'Guitar', categories: ['Noun'] },
  { id: nanoid(), text: 'House', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Hat', categories: ['Noun'] },
  { id: nanoid(), text: 'Hand', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Heart', categories: ['Noun'] },
  { id: nanoid(), text: 'Horse', categories: ['Noun'] }, { id: nanoid(), text: 'Hill', categories: ['Noun'] },
  { id: nanoid(), text: 'Home', categories: ['Noun', 'Adverb'] }, { id: nanoid(), text: 'Hour', categories: ['Noun'] },
  { id: nanoid(), text: 'Help', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Hope', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Hit', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'History', categories: ['Noun'] },
  { id: nanoid(), text: 'Holiday', categories: ['Noun'] }, { id: nanoid(), text: 'Hospital', categories: ['Noun'] },
  { id: nanoid(), text: 'Happiness', categories: ['Noun'] },
  { id: nanoid(), text: 'Idea', categories: ['Noun'] }, { id: nanoid(), text: 'Ink', categories: ['Noun'] },
  { id: nanoid(), text: 'Island', categories: ['Noun'] }, { id: nanoid(), text: 'Iron', categories: ['Noun', 'Verb', 'Adjective'] },
  { id: nanoid(), text: 'Ice', categories: ['Noun'] }, { id: nanoid(), text: 'Image', categories: ['Noun'] },
  { id: nanoid(), text: 'Insect', categories: ['Noun'] }, { id: nanoid(), text: 'Instrument', categories: ['Noun'] },
  { id: nanoid(), text: 'Information', categories: ['Noun'] }, { id: nanoid(), text: 'Industry', categories: ['Noun'] },
  { id: nanoid(), text: 'Jam', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Jewel', categories: ['Noun'] },
  { id: nanoid(), text: 'Job', categories: ['Noun'] }, { id: nanoid(), text: 'Joke', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Juice', categories: ['Noun'] }, { id: nanoid(), text: 'Journey', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Judge', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Jungle', categories: ['Noun'] },
  { id: nanoid(), text: 'Jacket', categories: ['Noun'] },
  { id: nanoid(), text: 'Key', categories: ['Noun'] }, { id: nanoid(), text: 'King', categories: ['Noun'] },
  { id: nanoid(), text: 'Kite', categories: ['Noun'] }, { id: nanoid(), text: 'Kitchen', categories: ['Noun'] },
  { id: nanoid(), text: 'Kid', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Knife', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Kick', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Kiss', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Knowledge', categories: ['Noun'] }, { id: nanoid(), text: 'Kangaroo', categories: ['Noun'] },
  { id: nanoid(), text: 'Lamp', categories: ['Noun'] }, { id: nanoid(), text: 'Leaf', categories: ['Noun'] },
  { id: nanoid(), text: 'Lion', categories: ['Noun'] }, { id: nanoid(), text: 'Lake', categories: ['Noun'] },
  { id: nanoid(), text: 'Love', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Light', categories: ['Noun', 'Verb', 'Adjective'] },
  { id: nanoid(), text: 'Look', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Laugh', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Language', categories: ['Noun'] }, { id: nanoid(), text: 'Library', categories: ['Noun'] },
  { id: nanoid(), text: 'Lemon', categories: ['Noun'] },
  { id: nanoid(), text: 'Man', categories: ['Noun'] }, { id: nanoid(), text: 'Moon', categories: ['Noun'] },
  { id: nanoid(), text: 'Mouse', categories: ['Noun'] }, { id: nanoid(), text: 'Map', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Music', categories: ['Noun'] }, { id: nanoid(), text: 'Mountain', categories: ['Noun'] },
  { id: nanoid(), text: 'Morning', categories: ['Noun'] }, { id: nanoid(), text: 'Money', categories: ['Noun'] },
  { id: nanoid(), text: 'Move', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Machine', categories: ['Noun'] },
  { id: nanoid(), text: 'Market', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Moment', categories: ['Noun'] },
  { id: nanoid(), text: 'Magic', categories: ['Noun', 'Adjective'] },
  { id: nanoid(), text: 'Nest', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Night', categories: ['Noun'] },
  { id: nanoid(), text: 'Nose', categories: ['Noun'] }, { id: nanoid(), text: 'Note', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Name', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Number', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Need', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Nature', categories: ['Noun'] },
  { id: nanoid(), text: 'Newspaper', categories: ['Noun'] }, { id: nanoid(), text: 'Neighbor', categories: ['Noun'] },
  { id: nanoid(), text: 'Noise', categories: ['Noun'] },
  { id: nanoid(), text: 'Orange', categories: ['Noun', 'Adjective'] }, { id: nanoid(), text: 'Owl', categories: ['Noun'] },
  { id: nanoid(), text: 'Ocean', categories: ['Noun'] }, { id: nanoid(), text: 'Oil', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Office', categories: ['Noun'] }, { id: nanoid(), text: 'Order', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Opportunity', categories: ['Noun'] }, { id: nanoid(), text: 'Operation', categories: ['Noun'] },
  { id: nanoid(), text: 'Opinion', categories: ['Noun'] },
  { id: nanoid(), text: 'Park', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Pen', categories: ['Noun'] }, // Pen (writing) vs Pen (animal enclosure, Verb)
  { id: nanoid(), text: 'Pig', categories: ['Noun'] }, { id: nanoid(), text: 'Pizza', categories: ['Noun'] },
  { id: nanoid(), text: 'Plant', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Path', categories: ['Noun'] },
  { id: nanoid(), text: 'Paper', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Party', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Play', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Paint', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Pass', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Planet', categories: ['Noun'] },
  { id: nanoid(), text: 'Picture', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Problem', categories: ['Noun'] },
  { id: nanoid(), text: 'Power', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Queen', categories: ['Noun'] }, { id: nanoid(), text: 'Quest', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Quilt', categories: ['Noun'] }, { id: nanoid(), text: 'Question', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Quiet', categories: ['Noun', 'Adjective', 'Verb'] }, { id: nanoid(), text: 'Quality', categories: ['Noun'] },
  { id: nanoid(), text: 'Quantity', categories: ['Noun'] },
  { id: nanoid(), text: 'Rain', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Ring', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Road', categories: ['Noun'] }, { id: nanoid(), text: 'Rock', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Room', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'River', categories: ['Noun'] },
  { id: nanoid(), text: 'Run', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Rest', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Ride', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Rainbow', categories: ['Noun'] },
  { id: nanoid(), text: 'Restaurant', categories: ['Noun'] }, { id: nanoid(), text: 'Reason', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Reflection', categories: ['Noun'] },
  { id: nanoid(), text: 'Sun', categories: ['Noun'] }, { id: nanoid(), text: 'Star', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Ship', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Shoe', categories: ['Noun'] },
  { id: nanoid(), text: 'School', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Song', categories: ['Noun'] },
  { id: nanoid(), text: 'Story', categories: ['Noun'] }, // story (verb) is less common
  { id: nanoid(), text: 'Street', categories: ['Noun'] },
  { id: nanoid(), text: 'Start', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Sleep', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Study', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Summer', categories: ['Noun'] },
  { id: nanoid(), text: 'Science', categories: ['Noun'] }, { id: nanoid(), text: 'Solution', categories: ['Noun'] },
  { id: nanoid(), text: 'Space', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Table', categories: ['Noun'] }, // Table (verb) as in 'table a motion'
  { id: nanoid(), text: 'Tree', categories: ['Noun'] },
  { id: nanoid(), text: 'Train', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Time', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Tiger', categories: ['Noun'] }, { id: nanoid(), text: 'Town', categories: ['Noun'] },
  { id: nanoid(), text: 'Toy', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Team', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Talk', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Try', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Turn', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Technology', categories: ['Noun'] },
  { id: nanoid(), text: 'Treasure', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Telephone', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Television', categories: ['Noun'] },
  { id: nanoid(), text: 'Umbrella', categories: ['Noun'] }, { id: nanoid(), text: 'Uncle', categories: ['Noun'] },
  { id: nanoid(), text: 'Unit', categories: ['Noun'] }, { id: nanoid(), text: 'User', categories: ['Noun'] },
  { id: nanoid(), text: 'Use', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Universe', categories: ['Noun'] },
  { id: nanoid(), text: 'Understanding', categories: ['Noun'] },
  { id: nanoid(), text: 'Van', categories: ['Noun'] }, { id: nanoid(), text: 'Vase', categories: ['Noun'] },
  { id: nanoid(), text: 'Violin', categories: ['Noun'] }, { id: nanoid(), text: 'Village', categories: ['Noun'] },
  { id: nanoid(), text: 'Voice', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Value', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Visit', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Victory', categories: ['Noun'] },
  { id: nanoid(), text: 'Volcano', categories: ['Noun'] },
  { id: nanoid(), text: 'Water', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Wind', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Wolf', categories: ['Noun'] }, { id: nanoid(), text: 'Woman', categories: ['Noun'] },
  { id: nanoid(), text: 'World', categories: ['Noun'] }, { id: nanoid(), text: 'Window', categories: ['Noun'] },
  { id: nanoid(), text: 'Word', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Week', categories: ['Noun'] },
  { id: nanoid(), text: 'Work', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Watch', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Wish', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Winter', categories: ['Noun'] },
  { id: nanoid(), text: 'Website', categories: ['Noun'] }, { id: nanoid(), text: 'Weather', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Wisdom', categories: ['Noun'] },
  { id: nanoid(), text: 'Xylophone', categories: ['Noun'] },
  { id: nanoid(), text: 'Yarn', categories: ['Noun'] }, { id: nanoid(), text: 'Yak', categories: ['Noun'] },
  { id: nanoid(), text: 'Yard', categories: ['Noun'] }, { id: nanoid(), text: 'Yacht', categories: ['Noun'] },
  { id: nanoid(), text: 'Year', categories: ['Noun'] }, { id: nanoid(), text: 'Youth', categories: ['Noun'] },
  { id: nanoid(), text: 'Yell', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Yawn', categories: ['Noun', 'Verb'] },
  { id: nanoid(), text: 'Yoga', categories: ['Noun'] },
  { id: nanoid(), text: 'Zebra', categories: ['Noun'] }, { id: nanoid(), text: 'Zoo', categories: ['Noun'] },
  { id: nanoid(), text: 'Zone', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Zero', categories: ['Noun', 'Adjective', 'Verb'] },
  { id: nanoid(), text: 'Zip', categories: ['Noun', 'Verb'] }, { id: nanoid(), text: 'Zoom', categories: ['Noun', 'Verb'] },

  // Verbs (Main verbs) - some already covered if also Noun
  { id: nanoid(), text: 'Ask', categories: ['Verb'] },
  { id: nanoid(), text: 'Add', categories: ['Verb'] },{ id: nanoid(), text: 'Arrive', categories: ['Verb'] },
  { id: nanoid(), text: 'Agree', categories: ['Verb'] }, { id: nanoid(), text: 'Allow', categories: ['Verb'] },
  { id: nanoid(), text: 'Analyze', categories: ['Verb'] }, { id: nanoid(), text: 'Announce', categories: ['Verb'] },
  { id: nanoid(), text: 'Appear', categories: ['Verb'] },
  { id: nanoid(), text: 'Bring', categories: ['Verb'] }, { id: nanoid(), text: 'Build', categories: ['Verb'] },
  { id: nanoid(), text: 'Buy', categories: ['Verb'] }, { id: nanoid(), text: 'Begin', categories: ['Verb'] },
  { id: nanoid(), text: 'Bake', categories: ['Verb'] }, { id: nanoid(), text: 'Believe', categories: ['Verb'] },
  { id: nanoid(), text: 'Break', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Breathe', categories: ['Verb'] },
  { id: nanoid(), text: 'Calculate', categories: ['Verb'] }, { id: nanoid(), text: 'Celebrate', categories: ['Verb'] },
  { id: nanoid(), text: 'Come', categories: ['Verb'] },
  { id: nanoid(), text: 'Clean', categories: ['Verb', 'Adjective'] },
  { id: nanoid(), text: 'Climb', categories: ['Verb'] },
  { id: nanoid(), text: 'Choose', categories: ['Verb'] }, { id: nanoid(), text: 'Continue', categories: ['Verb'] },
  { id: nanoid(), text: 'Create', categories: ['Verb'] }, { id: nanoid(), text: 'Communicate', categories: ['Verb'] },
  { id: nanoid(), text: 'Consider', categories: ['Verb'] },
  { id: nanoid(), text: 'Decide', categories: ['Verb'] }, { id: nanoid(), text: 'Describe', categories: ['Verb'] },
  { id: nanoid(), text: 'Develop', categories: ['Verb'] }, { id: nanoid(), text: 'Discover', categories: ['Verb'] },
  { id: nanoid(), text: 'Discuss', categories: ['Verb'] },
  { id: nanoid(), text: 'Eat', categories: ['Verb'] },
  { id: nanoid(), text: 'Enjoy', categories: ['Verb'] }, { id: nanoid(), text: 'Enter', categories: ['Verb'] },
  { id: nanoid(), text: 'Explain', categories: ['Verb'] }, { id: nanoid(), text: 'Earn', categories: ['Verb'] },
  { id: nanoid(), text: 'Explore', categories: ['Verb'] }, { id: nanoid(), text: 'Establish', categories: ['Verb'] },
  { id: nanoid(), text: 'Examine', categories: ['Verb'] },
  { id: nanoid(), text: 'Find', categories: ['Verb'] },
  { id: nanoid(), text: 'Feel', categories: ['Verb'] }, { id: nanoid(), text: 'Fight', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Follow', categories: ['Verb'] }, { id: nanoid(), text: 'Forget', categories: ['Verb'] },
  { id: nanoid(), text: 'Finish', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Forgive', categories: ['Verb'] },
  { id: nanoid(), text: 'Function', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Go', categories: ['Verb'] }, { id: nanoid(), text: 'Get', categories: ['Verb'] },
  { id: nanoid(), text: 'Give', categories: ['Verb'] }, { id: nanoid(), text: 'Grow', categories: ['Verb'] },
  { id: nanoid(), text: 'Guess', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Gain', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Guide', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Generate', categories: ['Verb'] },
  { id: nanoid(), text: 'Govern', categories: ['Verb'] },
  { id: nanoid(), text: 'Hold', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Hear', categories: ['Verb'] },
  { id: nanoid(), text: 'Happen', categories: ['Verb'] }, { id: nanoid(), text: 'Handle', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Hesitate', categories: ['Verb'] },
  { id: nanoid(), text: 'Imagine', categories: ['Verb'] },
  { id: nanoid(), text: 'Invite', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Inform', categories: ['Verb'] },
  { id: nanoid(), text: 'Improve', categories: ['Verb'] }, { id: nanoid(), text: 'Investigate', categories: ['Verb'] },
  { id: nanoid(), text: 'Introduce', categories: ['Verb'] },
  { id: nanoid(), text: 'Jump', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Join', categories: ['Verb'] },
  { id: nanoid(), text: 'Justify', categories: ['Verb'] },
  { id: nanoid(), text: 'Keep', categories: ['Verb'] }, { id: nanoid(), text: 'Know', categories: ['Verb'] },
  { id: nanoid(), text: 'Kill', categories: ['Verb'] },
  { id: nanoid(), text: 'Like', categories: ['Verb', 'Preposition'] },
  { id: nanoid(), text: 'Learn', categories: ['Verb'] }, { id: nanoid(), text: 'Listen', categories: ['Verb'] },
  { id: nanoid(), text: 'Live', categories: ['Verb', 'Adjective', 'Adverb'] }, { id: nanoid(), text: 'Leave', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Lose', categories: ['Verb'] }, { id: nanoid(), text: 'Launch', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Make', categories: ['Verb'] },
  { id: nanoid(), text: 'Meet', categories: ['Verb'] }, { id: nanoid(), text: 'Mean', categories: ['Verb', 'Adjective', 'Noun'] },
  { id: nanoid(), text: 'Manage', categories: ['Verb'] }, { id: nanoid(), text: 'Measure', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Motivate', categories: ['Verb'] }, { id: nanoid(), text: 'Maintain', categories: ['Verb'] },
  { id: nanoid(), text: 'Notice', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Navigate', categories: ['Verb'] },
  { id: nanoid(), text: 'Negotiate', categories: ['Verb'] },
  { id: nanoid(), text: 'Open', categories: ['Verb', 'Adjective'] },
  { id: nanoid(), text: 'Offer', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Own', categories: ['Verb', 'Adjective'] }, // Own (adj) as in 'my own book'
  { id: nanoid(), text: 'Organize', categories: ['Verb'] }, { id: nanoid(), text: 'Observe', categories: ['Verb'] },
  { id: nanoid(), text: 'Operate', categories: ['Verb'] },
  { id: nanoid(), text: 'Put', categories: ['Verb'] },
  { id: nanoid(), text: 'Pay', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Prepare', categories: ['Verb'] },
  { id: nanoid(), text: 'Promise', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Provide', categories: ['Verb'] },
  { id: nanoid(), text: 'Publish', categories: ['Verb'] }, { id: nanoid(), text: 'Participate', categories: ['Verb'] },
  { id: nanoid(), text: 'Persuade', categories: ['Verb'] },
  { id: nanoid(), text: 'Quit', categories: ['Verb'] }, { id: nanoid(), text: 'Qualify', categories: ['Verb'] },
  { id: nanoid(), text: 'Question', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Read', categories: ['Verb'] },
  { id: nanoid(), text: 'Reply', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Remember', categories: ['Verb'] },
  { id: nanoid(), text: 'Reach', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Receive', categories: ['Verb'] },
  { id: nanoid(), text: 'Reduce', categories: ['Verb'] }, { id: nanoid(), text: 'Recommend', categories: ['Verb'] },
  { id: nanoid(), text: 'Represent', categories: ['Verb'] },
  { id: nanoid(), text: 'See', categories: ['Verb'] }, { id: nanoid(), text: 'Say', categories: ['Verb'] },
  { id: nanoid(), text: 'Sing', categories: ['Verb'] },
  { id: nanoid(), text: 'Swim', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Speak', categories: ['Verb'] }, { id: nanoid(), text: 'Solve', categories: ['Verb'] },
  { id: nanoid(), text: 'Succeed', categories: ['Verb'] }, { id: nanoid(), text: 'Suggest', categories: ['Verb'] },
  { id: nanoid(), text: 'Support', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Take', categories: ['Verb'] },
  { id: nanoid(), text: 'Teach', categories: ['Verb'] }, { id: nanoid(), text: 'Tell', categories: ['Verb'] },
  { id: nanoid(), text: 'Think', categories: ['Verb'] }, { id: nanoid(), text: 'Travel', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Transform', categories: ['Verb'] }, { id: nanoid(), text: 'Translate', categories: ['Verb'] },
  { id: nanoid(), text: 'Understand', categories: ['Verb'] },
  { id: nanoid(), text: 'Unite', categories: ['Verb'] }, { id: nanoid(), text: 'Update', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Utilize', categories: ['Verb'] },
  { id: nanoid(), text: 'Vote', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Vanish', categories: ['Verb'] }, { id: nanoid(), text: 'Verify', categories: ['Verb'] },
  { id: nanoid(), text: 'Volunteer', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Wait', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Walk', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Want', categories: ['Verb'] }, // Want (noun) is rare
  { id: nanoid(), text: 'Write', categories: ['Verb'] },
  { id: nanoid(), text: 'Win', categories: ['Verb', 'Noun'] }, { id: nanoid(), text: 'Wonder', categories: ['Verb', 'Noun'] },
  { id: nanoid(), text: 'Welcome', categories: ['Verb', 'Noun', 'Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Yield', categories: ['Verb', 'Noun'] },

  // Auxiliary Verbs (Duplicates for frequency, already categorized as Verb)
  { id: nanoid(), text: 'Do', categories: ['Verb'] }, { id: nanoid(), text: 'Do', categories: ['Verb'] }, 
  { id: nanoid(), text: 'Does', categories: ['Verb'] }, { id: nanoid(), text: 'Does', categories: ['Verb'] },
  { id: nanoid(), text: 'Did', categories: ['Verb'] }, { id: nanoid(), text: 'Did', categories: ['Verb'] },
  { id: nanoid(), text: 'Did', categories: ['Verb'] },
  { id: nanoid(), text: 'Am', categories: ['Verb'] }, { id: nanoid(), text: 'Is', categories: ['Verb'] },
  { id: nanoid(), text: 'Is', categories: ['Verb'] }, { id: nanoid(), text: 'Is', categories: ['Verb'] },
  { id: nanoid(), text: 'Are', categories: ['Verb'] }, { id: nanoid(), text: 'Are', categories: ['Verb'] },
  { id: nanoid(), text: 'Was', categories: ['Verb'] }, { id: nanoid(), text: 'Was', categories: ['Verb'] },
  { id: nanoid(), text: 'Were', categories: ['Verb'] }, { id: nanoid(), text: 'Were', categories: ['Verb'] },
  { id: nanoid(), text: 'Be', categories: ['Verb'] }, { id: nanoid(), text: 'Been', categories: ['Verb'] },
  { id: nanoid(), text: 'Has', categories: ['Verb'] }, { id: nanoid(), text: 'Has', categories: ['Verb'] },
  { id: nanoid(), text: 'Have', categories: ['Verb'] }, { id: nanoid(), text: 'Have', categories: ['Verb'] },
  { id: nanoid(), text: 'Have', categories: ['Verb'] },
  { id: nanoid(), text: 'Had', categories: ['Verb'] }, { id: nanoid(), text: 'Had', categories: ['Verb'] },
  { id: nanoid(), text: 'Can', categories: ['Verb'] }, { id: nanoid(), text: 'Can', categories: ['Verb'] },
  { id: nanoid(), text: 'Could', categories: ['Verb'] }, { id: nanoid(), text: 'Could', categories: ['Verb'] },
  { id: nanoid(), text: 'Will', categories: ['Verb'] }, { id: nanoid(), text: 'Will', categories: ['Verb'] },
  { id: nanoid(), text: 'Would', categories: ['Verb'] }, { id: nanoid(), text: 'Would', categories: ['Verb'] },
  { id: nanoid(), text: 'Should', categories: ['Verb'] }, { id: nanoid(), text: 'Should', categories: ['Verb'] },
  { id: nanoid(), text: 'May', categories: ['Verb'] }, { id: nanoid(), text: 'May', categories: ['Verb'] },
  { id: nanoid(), text: 'Might', categories: ['Verb'] }, { id: nanoid(), text: 'Might', categories: ['Verb'] },
  { id: nanoid(), text: 'Must', categories: ['Verb'] }, { id: nanoid(), text: 'Must', categories: ['Verb'] },


  // Adjectives
  { id: nanoid(), text: 'Angry', categories: ['Adjective'] }, { id: nanoid(), text: 'Able', categories: ['Adjective'] },
  { id: nanoid(), text: 'Awful', categories: ['Adjective'] }, { id: nanoid(), text: 'Active', categories: ['Adjective'] },
  { id: nanoid(), text: 'Amazing', categories: ['Adjective'] }, { id: nanoid(), text: 'Ancient', categories: ['Adjective'] },
  { id: nanoid(), text: 'Authentic', categories: ['Adjective'] }, { id: nanoid(), text: 'Automatic', categories: ['Adjective'] },
  { id: nanoid(), text: 'Big', categories: ['Adjective'] }, { id: nanoid(), text: 'Blue', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Bad', categories: ['Adjective'] }, { id: nanoid(), text: 'Best', categories: ['Adjective', 'Adverb', 'Noun', 'Verb'] },
  { id: nanoid(), text: 'Busy', categories: ['Adjective', 'Verb'] }, { id: nanoid(), text: 'Brave', categories: ['Adjective'] },
  { id: nanoid(), text: 'Bright', categories: ['Adjective', 'Adverb', 'Verb'] }, { id: nanoid(), text: 'Beautiful', categories: ['Adjective'] },
  { id: nanoid(), text: 'Bitter', categories: ['Adjective', 'Noun'] }, { id: nanoid(), text: 'Brilliant', categories: ['Adjective'] },
  { id: nanoid(), text: 'Beneficial', categories: ['Adjective'] },
  { id: nanoid(), text: 'Cold', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Clear', categories: ['Adjective', 'Adverb', 'Verb'] }, { id: nanoid(), text: 'Cute', categories: ['Adjective'] },
  { id: nanoid(), text: 'Calm', categories: ['Adjective', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Cool', categories: ['Adjective', 'Noun', 'Verb'] },
  { id: nanoid(), text: 'Crazy', categories: ['Adjective'] }, { id: nanoid(), text: 'Clever', categories: ['Adjective'] },
  { id: nanoid(), text: 'Colorful', categories: ['Adjective'] }, { id: nanoid(), text: 'Comfortable', categories: ['Adjective'] },
  { id: nanoid(), text: 'Creative', categories: ['Adjective'] }, { id: nanoid(), text: 'Critical', categories: ['Adjective'] },
  { id: nanoid(), text: 'Curious', categories: ['Adjective'] },
  { id: nanoid(), text: 'Dark', categories: ['Adjective', 'Noun'] }, { id: nanoid(), text: 'Dry', categories: ['Adjective', 'Verb'] },
  { id: nanoid(), text: 'Deep', categories: ['Adjective', 'Adverb', 'Noun'] }, { id: nanoid(), text: 'Dead', categories: ['Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Different', categories: ['Adjective'] }, { id: nanoid(), text: 'Difficult', categories: ['Adjective'] },
  { id: nanoid(), text: 'Dangerous', categories: ['Adjective'] }, { id: nanoid(), text: 'Delicious', categories: ['Adjective'] },
  { id: nanoid(), text: 'Delightful', categories: ['Adjective'] }, { id: nanoid(), text: 'Digital', categories: ['Adjective'] },
  { id: nanoid(), text: 'Dynamic', categories: ['Adjective'] },
  { id: nanoid(), text: 'Easy', categories: ['Adjective', 'Adverb'] }, { id: nanoid(), text: 'Empty', categories: ['Adjective', 'Verb', 'Noun'] },
  { id: nanoid(), text: 'Early', categories: ['Adjective', 'Adverb'] }, { id: nanoid(), text: 'Evil', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Excited', categories: ['Adjective'] }, { id: nanoid(), text: 'Elegant', categories: ['Adjective'] },
  { id: nanoid(), text: 'Excellent', categories: ['Adjective'] }, { id: nanoid(), text: 'Expensive', categories: ['Adjective'] },
  { id: nanoid(), text: 'Effective', categories: ['Adjective'] }, { id: nanoid(), text: 'Efficient', categories: ['Adjective'] },
  { id: nanoid(), text: 'Fast', categories: ['Adjective', 'Adverb', 'Verb', 'Noun'] }, { id: nanoid(), text: 'Full', categories: ['Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Free', categories: ['Adjective', 'Adverb', 'Verb'] }, { id: nanoid(), text: 'Fresh', categories: ['Adjective', 'Verb'] },
  { id: nanoid(), text: 'Fine', categories: ['Adjective', 'Adverb', 'Verb', 'Noun'] }, { id: nanoid(), text: 'Fair', categories: ['Adjective', 'Adverb', 'Noun'] },
  { id: nanoid(), text: 'Famous', categories: ['Adjective'] }, { id: nanoid(), text: 'Funny', categories: ['Adjective'] },
  { id: nanoid(), text: 'Fantastic', categories: ['Adjective'] }, { id: nanoid(), text: 'Favorite', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Flexible', categories: ['Adjective'] },
  { id: nanoid(), text: 'Good', categories: ['Adjective', 'Noun', 'Adverb'] }, { id: nanoid(), text: 'Great', categories: ['Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Green', categories: ['Adjective', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Gentle', categories: ['Adjective'] },
  { id: nanoid(), text: 'Glad', categories: ['Adjective'] }, { id: nanoid(), text: 'Giant', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Grand', categories: ['Adjective'] }, { id: nanoid(), text: 'Golden', categories: ['Adjective'] },
  { id: nanoid(), text: 'Generous', categories: ['Adjective'] }, { id: nanoid(), text: 'Global', categories: ['Adjective'] },
  { id: nanoid(), text: 'Gorgeous', categories: ['Adjective'] },
  { id: nanoid(), text: 'Happy', categories: ['Adjective'] }, { id: nanoid(), text: 'Hard', categories: ['Adjective', 'Adverb'] },
  { id: nanoid(), text: 'High', categories: ['Adjective', 'Adverb', 'Noun'] }, { id: nanoid(), text: 'Hot', categories: ['Adjective'] },
  { id: nanoid(), text: 'Heavy', categories: ['Adjective', 'Adverb'] }, { id: nanoid(), text: 'Huge', categories: ['Adjective'] },
  { id: nanoid(), text: 'Honest', categories: ['Adjective'] }, { id: nanoid(), text: 'Hungry', categories: ['Adjective'] },
  { id: nanoid(), text: 'Helpful', categories: ['Adjective'] }, { id: nanoid(), text: 'Healthy', categories: ['Adjective'] },
  { id: nanoid(), text: 'Historical', categories: ['Adjective'] },
  { id: nanoid(), text: 'Important', categories: ['Adjective'] }, { id: nanoid(), text: 'Interesting', categories: ['Adjective'] },
  { id: nanoid(), text: 'Intelligent', categories: ['Adjective'] }, { id: nanoid(), text: 'Impossible', categories: ['Adjective'] },
  { id: nanoid(), text: 'Independent', categories: ['Adjective'] },
  { id: nanoid(), text: 'Kind', categories: ['Adjective', 'Noun'] }, { id: nanoid(), text: 'Keen', categories: ['Adjective'] },
  { id: nanoid(), text: 'Known', categories: ['Adjective'] },
  { id: nanoid(), text: 'Large', categories: ['Adjective'] }, { id: nanoid(), text: 'Little', categories: ['Adjective', 'Adverb', 'Pronoun'] },
  { id: nanoid(), text: 'Long', categories: ['Adjective', 'Adverb', 'Verb', 'Noun'] }, { id: nanoid(), text: 'Loud', categories: ['Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Low', categories: ['Adjective', 'Adverb', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Lovely', categories: ['Adjective'] },
  { id: nanoid(), text: 'Lucky', categories: ['Adjective'] }, { id: nanoid(), text: 'Luxurious', categories: ['Adjective'] },
  { id: nanoid(), text: 'Local', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Mad', categories: ['Adjective'] }, { id: nanoid(), text: 'Main', categories: ['Adjective'] },
  { id: nanoid(), text: 'Merry', categories: ['Adjective'] },
  { id: nanoid(), text: 'Modern', categories: ['Adjective'] }, { id: nanoid(), text: 'Mysterious', categories: ['Adjective'] },
  { id: nanoid(), text: 'Magical', categories: ['Adjective'] }, { id: nanoid(), text: 'Mechanical', categories: ['Adjective'] },
  { id: nanoid(), text: 'Musical', categories: ['Adjective'] },
  { id: nanoid(), text: 'New', categories: ['Adjective'] }, { id: nanoid(), text: 'Nice', categories: ['Adjective'] },
  { id: nanoid(), text: 'Near', categories: ['Adjective', 'Adverb', 'Preposition', 'Verb'] }, { id: nanoid(), text: 'Noisy', categories: ['Adjective'] },
  { id: nanoid(), text: 'Nervous', categories: ['Adjective'] }, { id: nanoid(), text: 'Natural', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'National', categories: ['Adjective'] }, { id: nanoid(), text: 'Negative', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Numerous', categories: ['Adjective'] },
  { id: nanoid(), text: 'Old', categories: ['Adjective'] },
  { id: nanoid(), text: 'Other', categories: ['Adjective', 'Pronoun', 'Noun'] },
  { id: nanoid(), text: 'Odd', categories: ['Adjective'] }, { id: nanoid(), text: 'Original', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Official', categories: ['Adjective', 'Noun'] }, { id: nanoid(), text: 'Open', categories: ['Adjective', 'Verb'] },
  { id: nanoid(), text: 'Ordinary', categories: ['Adjective'] },
  { id: nanoid(), text: 'Poor', categories: ['Adjective'] }, { id: nanoid(), text: 'Pretty', categories: ['Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Proud', categories: ['Adjective'] }, { id: nanoid(), text: 'Pure', categories: ['Adjective'] },
  { id: nanoid(), text: 'Perfect', categories: ['Adjective', 'Verb'] }, { id: nanoid(), text: 'Polite', categories: ['Adjective'] },
  { id: nanoid(), text: 'Powerful', categories: ['Adjective'] }, { id: nanoid(), text: 'Popular', categories: ['Adjective'] },
  { id: nanoid(), text: 'Positive', categories: ['Adjective', 'Noun'] }, { id: nanoid(), text: 'Practical', categories: ['Adjective'] },
  { id: nanoid(), text: 'Professional', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Quick', categories: ['Adjective', 'Adverb'] }, { id: nanoid(), text: 'Quiet', categories: ['Adjective', 'Noun', 'Verb'] },
  { id: nanoid(), text: 'Red', categories: ['Adjective', 'Noun'] }, { id: nanoid(), text: 'Rich', categories: ['Adjective'] },
  { id: nanoid(), text: 'Right', categories: ['Adjective', 'Adverb', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Rough', categories: ['Adjective', 'Noun', 'Verb'] },
  { id: nanoid(), text: 'Round', categories: ['Adjective', 'Adverb', 'Preposition', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Real', categories: ['Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Ready', categories: ['Adjective', 'Verb'] }, { id: nanoid(), text: 'Rare', categories: ['Adjective'] },
  { id: nanoid(), text: 'Regular', categories: ['Adjective'] }, { id: nanoid(), text: 'Responsible', categories: ['Adjective'] },
  { id: nanoid(), text: 'Royal', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Small', categories: ['Adjective'] }, { id: nanoid(), text: 'Sad', categories: ['Adjective'] },
  { id: nanoid(), text: 'Slow', categories: ['Adjective', 'Adverb', 'Verb'] }, { id: nanoid(), text: 'Soft', categories: ['Adjective'] },
  { id: nanoid(), text: 'Strong', categories: ['Adjective'] }, { id: nanoid(), text: 'Sweet', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Sour', categories: ['Adjective', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Simple', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Sure', categories: ['Adjective', 'Adverb'] }, { id: nanoid(), text: 'Special', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Successful', categories: ['Adjective'] }, { id: nanoid(), text: 'Serious', categories: ['Adjective'] },
  { id: nanoid(), text: 'Scientific', categories: ['Adjective'] },
  { id: nanoid(), text: 'Tall', categories: ['Adjective'] }, { id: nanoid(), text: 'Thin', categories: ['Adjective', 'Verb'] },
  { id: nanoid(), text: 'True', categories: ['Adjective', 'Adverb', 'Verb'] }, { id: nanoid(), text: 'Tiny', categories: ['Adjective'] },
  { id: nanoid(), text: 'Tired', categories: ['Adjective'] }, { id: nanoid(), text: 'Thick', categories: ['Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Thankful', categories: ['Adjective'] }, { id: nanoid(), text: 'Thoughtful', categories: ['Adjective'] },
  { id: nanoid(), text: 'Traditional', categories: ['Adjective'] }, { id: nanoid(), text: 'Typical', categories: ['Adjective'] },
  { id: nanoid(), text: 'Terrible', categories: ['Adjective'] },
  { id: nanoid(), text: 'Ugly', categories: ['Adjective'] }, { id: nanoid(), text: 'Unusual', categories: ['Adjective'] },
  { id: nanoid(), text: 'Useful', categories: ['Adjective'] }, { id: nanoid(), text: 'Unique', categories: ['Adjective'] },
  { id: nanoid(), text: 'Urgent', categories: ['Adjective'] },
  { id: nanoid(), text: 'Vast', categories: ['Adjective'] }, { id: nanoid(), text: 'Violet', categories: ['Adjective', 'Noun'] },
  { id: nanoid(), text: 'Valuable', categories: ['Adjective', 'Noun'] }, { id: nanoid(), text: 'Various', categories: ['Adjective'] },
  { id: nanoid(), text: 'Virtual', categories: ['Adjective'] },
  { id: nanoid(), text: 'Warm', categories: ['Adjective', 'Verb'] }, { id: nanoid(), text: 'Wet', categories: ['Adjective', 'Verb', 'Noun'] },
  { id: nanoid(), text: 'White', categories: ['Adjective', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Wide', categories: ['Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Wild', categories: ['Adjective', 'Adverb', 'Noun'] }, { id: nanoid(), text: 'Wise', categories: ['Adjective'] },
  { id: nanoid(), text: 'Wrong', categories: ['Adjective', 'Adverb', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Wonderful', categories: ['Adjective'] },
  { id: nanoid(), text: 'Weak', categories: ['Adjective'] }, { id: nanoid(), text: 'Wooden', categories: ['Adjective'] },
  { id: nanoid(), text: 'Wealthy', categories: ['Adjective'] },
  { id: nanoid(), text: 'Young', categories: ['Adjective', 'Noun'] }, { id: nanoid(), text: 'Yellow', categories: ['Adjective', 'Noun', 'Verb'] },
  { id: nanoid(), text: 'Yummy', categories: ['Adjective'] },
  { id: nanoid(), text: 'Zany', categories: ['Adjective'] }, { id: nanoid(), text: 'Zealous', categories: ['Adjective'] },

  // Adverbs - many already covered
  { id: nanoid(), text: 'Always', categories: ['Adverb'] }, { id: nanoid(), text: 'Almost', categories: ['Adverb'] },
  { id: nanoid(), text: 'Again', categories: ['Adverb'] }, { id: nanoid(), text: 'Also', categories: ['Adverb'] },
  { id: nanoid(), text: 'Actually', categories: ['Adverb'] }, { id: nanoid(), text: 'Abroad', categories: ['Adverb'] },
  { id: nanoid(), text: 'Additionally', categories: ['Adverb'] }, { id: nanoid(), text: 'Absolutely', categories: ['Adverb'] },
  { id: nanoid(), text: 'Badly', categories: ['Adverb'] }, { id: nanoid(), text: 'Barely', categories: ['Adverb'] },
  { id: nanoid(), text: 'Beautifully', categories: ['Adverb'] }, { id: nanoid(), text: 'Bravely', categories: ['Adverb'] },
  { id: nanoid(), text: 'Brightly', categories: ['Adverb'] }, { id: nanoid(), text: 'Briefly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Carefully', categories: ['Adverb'] },
  { id: nanoid(), text: 'Certainly', categories: ['Adverb'] }, { id: nanoid(), text: 'Completely', categories: ['Adverb'] },
  { id: nanoid(), text: 'Clearly', categories: ['Adverb'] }, { id: nanoid(), text: 'Consequently', categories: ['Adverb'] },
  { id: nanoid(), text: 'Constantly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Daily', categories: ['Adverb', 'Adjective'] }, { id: nanoid(), text: 'Deeply', categories: ['Adverb'] },
  { id: nanoid(), text: 'Directly', categories: ['Adverb'] }, { id: nanoid(), text: 'Differently', categories: ['Adverb'] },
  { id: nanoid(), text: 'Deliberately', categories: ['Adverb'] },
  { id: nanoid(), text: 'Enough', categories: ['Adverb', 'Adjective', 'Pronoun'] }, { id: nanoid(), text: 'Even', categories: ['Adverb', 'Adjective'] },
  { id: nanoid(), text: 'Exactly', categories: ['Adverb'] }, { id: nanoid(), text: 'Especially', categories: ['Adverb'] },
  { id: nanoid(), text: 'Eventually', categories: ['Adverb'] }, { id: nanoid(), text: 'Easily', categories: ['Adverb'] },
  { id: nanoid(), text: 'Extremely', categories: ['Adverb'] },
  { id: nanoid(), text: 'Finally', categories: ['Adverb'] },
  { id: nanoid(), text: 'Freely', categories: ['Adverb'] }, { id: nanoid(), text: 'Fully', categories: ['Adverb'] },
  { id: nanoid(), text: 'Forward', categories: ['Adverb', 'Adjective', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Fortunately', categories: ['Adverb'] },
  { id: nanoid(), text: 'Frequently', categories: ['Adverb'] }, { id: nanoid(), text: 'Fairly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Gently', categories: ['Adverb'] }, { id: nanoid(), text: 'Gladly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Generally', categories: ['Adverb'] }, { id: nanoid(), text: 'Greatly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Gradually', categories: ['Adverb'] },
  { id: nanoid(), text: 'Here', categories: ['Adverb'] },
  { id: nanoid(), text: 'Highly', categories: ['Adverb'] }, { id: nanoid(), text: 'However', categories: ['Adverb', 'Conjunction'] },
  { id: nanoid(), text: 'Honestly', categories: ['Adverb'] }, { id: nanoid(), text: 'Hopefully', categories: ['Adverb'] },
  { id: nanoid(), text: 'Hardly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Inside', categories: ['Adverb', 'Preposition', 'Noun', 'Adjective'] }, { id: nanoid(), text: 'Instead', categories: ['Adverb'] },
  { id: nanoid(), text: 'Immediately', categories: ['Adverb'] }, { id: nanoid(), text: 'Indeed', categories: ['Adverb'] },
  { id: nanoid(), text: 'Incredibly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Just', categories: ['Adverb', 'Adjective'] }, { id: nanoid(), text: 'Kindly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Keenly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Late', categories: ['Adverb', 'Adjective'] }, { id: nanoid(), text: 'Later', categories: ['Adverb', 'Adjective'] },
  { id: nanoid(), text: 'Loudly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Likely', categories: ['Adverb', 'Adjective'] }, { id: nanoid(), text: 'Largely', categories: ['Adverb'] },
  { id: nanoid(), text: 'Maybe', categories: ['Adverb'] }, { id: nanoid(), text: 'More', categories: ['Adverb', 'Adjective', 'Pronoun'] },
  { id: nanoid(), text: 'Much', categories: ['Adverb', 'Adjective', 'Pronoun'] }, { id: nanoid(), text: 'Madly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Mainly', categories: ['Adverb'] }, { id: nanoid(), text: 'Merely', categories: ['Adverb'] },
  { id: nanoid(), text: 'Meanwhile', categories: ['Adverb'] },
  { id: nanoid(), text: 'Nearly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Never', categories: ['Adverb'] }, { id: nanoid(), text: 'Next', categories: ['Adverb', 'Adjective', 'Noun', 'Preposition'] },
  { id: nanoid(), text: 'Now', categories: ['Adverb', 'Noun', 'Conjunction'] }, { id: nanoid(), text: 'Nicely', categories: ['Adverb'] },
  { id: nanoid(), text: 'Normally', categories: ['Adverb'] }, { id: nanoid(), text: 'Notably', categories: ['Adverb'] },
  { id: nanoid(), text: 'Naturally', categories: ['Adverb'] },
  { id: nanoid(), text: 'Often', categories: ['Adverb'] }, { id: nanoid(), text: 'Once', categories: ['Adverb', 'Conjunction', 'Noun'] },
  { id: nanoid(), text: 'Only', categories: ['Adverb', 'Adjective', 'Conjunction'] }, { id: nanoid(), text: 'Outside', categories: ['Adverb', 'Preposition', 'Noun', 'Adjective'] },
  { id: nanoid(), text: 'Over', categories: ['Adverb', 'Preposition'] }, { id: nanoid(), text: 'Openly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Otherwise', categories: ['Adverb'] }, { id: nanoid(), text: 'Occasionally', categories: ['Adverb'] },
  { id: nanoid(), text: 'Officially', categories: ['Adverb'] },
  { id: nanoid(), text: 'Politely', categories: ['Adverb'] }, { id: nanoid(), text: 'Poorly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Perhaps', categories: ['Adverb'] }, { id: nanoid(), text: 'Probably', categories: ['Adverb'] },
  { id: nanoid(), text: 'Previously', categories: ['Adverb'] }, { id: nanoid(), text: 'Particularly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Perfectly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Quickly', categories: ['Adverb'] }, { id: nanoid(), text: 'Quietly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Quite', categories: ['Adverb'] },
  { id: nanoid(), text: 'Rarely', categories: ['Adverb'] }, { id: nanoid(), text: 'Really', categories: ['Adverb'] },
  { id: nanoid(), text: 'Roughly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Rapidly', categories: ['Adverb'] }, { id: nanoid(), text: 'Regularly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Recently', categories: ['Adverb'] },
  { id: nanoid(), text: 'Sadly', categories: ['Adverb'] }, { id: nanoid(), text: 'Seldom', categories: ['Adverb'] },
  { id: nanoid(), text: 'Slowly', categories: ['Adverb'] }, { id: nanoid(), text: 'So', categories: ['Adverb', 'Conjunction'] },
  { id: nanoid(), text: 'Soon', categories: ['Adverb'] }, { id: nanoid(), text: 'Still', categories: ['Adverb', 'Adjective', 'Noun', 'Verb'] },
  { id: nanoid(), text: 'Surely', categories: ['Adverb'] }, { id: nanoid(), text: 'Silently', categories: ['Adverb'] },
  { id: nanoid(), text: 'Sometimes', categories: ['Adverb'] }, { id: nanoid(), text: 'Strongly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Suddenly', categories: ['Adverb'] }, { id: nanoid(), text: 'Similarly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Seriously', categories: ['Adverb'] },
  { id: nanoid(), text: 'Then', categories: ['Adverb', 'Conjunction'] }, { id: nanoid(), text: 'There', categories: ['Adverb', 'Pronoun'] },
  { id: nanoid(), text: 'Today', categories: ['Adverb', 'Noun'] }, { id: nanoid(), text: 'Too', categories: ['Adverb'] },
  { id: nanoid(), text: 'Truly', categories: ['Adverb'] }, { id: nanoid(), text: 'Thus', categories: ['Adverb'] },
  { id: nanoid(), text: 'Together', categories: ['Adverb'] }, { id: nanoid(), text: 'Tomorrow', categories: ['Adverb', 'Noun'] },
  { id: nanoid(), text: 'Typically', categories: ['Adverb'] },
  { id: nanoid(), text: 'Under', categories: ['Adverb', 'Preposition'] }, { id: nanoid(), text: 'Usually', categories: ['Adverb'] },
  { id: nanoid(), text: 'Unfortunately', categories: ['Adverb'] }, { id: nanoid(), text: 'Upward', categories: ['Adverb'] },
  { id: nanoid(), text: 'Ultimately', categories: ['Adverb'] },
  { id: nanoid(), text: 'Very', categories: ['Adverb'] }, { id: nanoid(), text: 'Vaguely', categories: ['Adverb'] },
  { id: nanoid(), text: 'Virtually', categories: ['Adverb'] },
  { id: nanoid(), text: 'Well', categories: ['Adverb', 'Adjective', 'Noun', 'Verb'] }, { id: nanoid(), text: 'When', categories: ['Adverb', 'Conjunction', 'Pronoun'] },
  { id: nanoid(), text: 'Where', categories: ['Adverb', 'Conjunction', 'Pronoun'] }, { id: nanoid(), text: 'Why', categories: ['Adverb', 'Noun', 'Conjunction'] },
  { id: nanoid(), text: 'Wisely', categories: ['Adverb'] }, { id: nanoid(), text: 'Warmly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Weekly', categories: ['Adverb', 'Adjective'] }, { id: nanoid(), text: 'Wholeheartedly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Willingly', categories: ['Adverb'] },
  { id: nanoid(), text: 'Yesterday', categories: ['Adverb', 'Noun'] }, { id: nanoid(), text: 'Yet', categories: ['Adverb', 'Conjunction'] },
  { id: nanoid(), text: 'Yearly', categories: ['Adverb', 'Adjective'] },
  { id: nanoid(), text: 'Zestily', categories: ['Adverb'] },

  // Pronouns
  { id: nanoid(), text: 'I', categories: ['Pronoun'] }, { id: nanoid(), text: 'You', categories: ['Pronoun'] },
  { id: nanoid(), text: 'He', categories: ['Pronoun'] }, { id: nanoid(), text: 'She', categories: ['Pronoun'] },
  { id: nanoid(), text: 'It', categories: ['Pronoun'] }, { id: nanoid(), text: 'We', categories: ['Pronoun'] },
  { id: nanoid(), text: 'They', categories: ['Pronoun'] }, { id: nanoid(), text: 'Me', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Him', categories: ['Pronoun'] }, { id: nanoid(), text: 'Her', categories: ['Pronoun', 'Adjective'] }, 
  { id: nanoid(), text: 'Us', categories: ['Pronoun'] }, { id: nanoid(), text: 'Them', categories: ['Pronoun'] },
  { id: nanoid(), text: 'My', categories: ['Adjective'] }, // Possessive adjectives like My, Your, His are often treated as determiners (a type of adjective)
  { id: nanoid(), text: 'Your', categories: ['Adjective'] }, 
  { id: nanoid(), text: 'His', categories: ['Adjective', 'Pronoun'] }, // His (pronoun as in 'the book is his')
  { id: nanoid(), text: 'Its', categories: ['Adjective'] },
  { id: nanoid(), text: 'Our', categories: ['Adjective'] }, { id: nanoid(), text: 'Their', categories: ['Adjective'] },
  { id: nanoid(), text: 'Mine', categories: ['Pronoun'] }, { id: nanoid(), text: 'Yours', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Hers', categories: ['Pronoun'] }, { id: nanoid(), text: 'Ours', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Theirs', categories: ['Pronoun'] },
  { id: nanoid(), text: 'This', categories: ['Pronoun', 'Adjective', 'Adverb'] }, { id: nanoid(), text: 'That', categories: ['Pronoun', 'Adjective', 'Adverb', 'Conjunction'] }, 
  { id: nanoid(), text: 'These', categories: ['Pronoun', 'Adjective'] }, { id: nanoid(), text: 'Those', categories: ['Pronoun', 'Adjective'] },
  { id: nanoid(), text: 'Who', categories: ['Pronoun', 'Conjunction'] }, { id: nanoid(), text: 'What', categories: ['Pronoun', 'Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Which', categories: ['Pronoun', 'Adjective', 'Conjunction'] }, { id: nanoid(), text: 'Whom', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Whose', categories: ['Pronoun', 'Adjective'] }, 
  { id: nanoid(), text: 'Myself', categories: ['Pronoun'] }, { id: nanoid(), text: 'Yourself', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Himself', categories: ['Pronoun'] }, { id: nanoid(), text: 'Herself', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Itself', categories: ['Pronoun'] }, { id: nanoid(), text: 'Ourselves', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Themselves', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Someone', categories: ['Pronoun'] }, { id: nanoid(), text: 'Anyone', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Everyone', categories: ['Pronoun'] }, { id: nanoid(), text: 'No one', categories: ['Pronoun'] }, // "No one" is two words, often a pronoun phrase
  { id: nanoid(), text: 'Somebody', categories: ['Pronoun'] }, { id: nanoid(), text: 'Anybody', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Everybody', categories: ['Pronoun'] }, { id: nanoid(), text: 'Nobody', categories: ['Pronoun', 'Noun'] },
  { id: nanoid(), text: 'Something', categories: ['Pronoun'] }, { id: nanoid(), text: 'Anything', categories: ['Pronoun'] },
  { id: nanoid(), text: 'Everything', categories: ['Pronoun'] }, { id: nanoid(), text: 'Nothing', categories: ['Pronoun', 'Adverb', 'Noun'] },
  { id: nanoid(), text: 'Each', categories: ['Pronoun', 'Adjective'] }, { id: nanoid(), text: 'Either', categories: ['Pronoun', 'Adjective', 'Conjunction'] },
  { id: nanoid(), text: 'Neither', categories: ['Pronoun', 'Adjective', 'Conjunction'] }, { id: nanoid(), text: 'Both', categories: ['Pronoun', 'Adjective', 'Conjunction'] },
  { id: nanoid(), text: 'Few', categories: ['Pronoun', 'Adjective'] }, { id: nanoid(), text: 'Many', categories: ['Pronoun', 'Adjective'] },
  { id: nanoid(), text: 'Several', categories: ['Pronoun', 'Adjective'] }, { id: nanoid(), text: 'All', categories: ['Pronoun', 'Adjective', 'Adverb'] },
  { id: nanoid(), text: 'Some', categories: ['Pronoun', 'Adjective', 'Adverb'] }, { id: nanoid(), text: 'Any', categories: ['Pronoun', 'Adjective', 'Adverb'] },
  { id: nanoid(), text: 'None', categories: ['Pronoun', 'Adverb'] },
  
  // Articles
  { id: nanoid(), text: 'A', categories: ['Article'] }, { id: nanoid(), text: 'A', categories: ['Article'] },
  { id: nanoid(), text: 'A', categories: ['Article'] }, { id: nanoid(), text: 'A', categories: ['Article'] },
  { id: nanoid(), text: 'A', categories: ['Article'] }, { id: nanoid(), text: 'A', categories: ['Article'] },
  { id: nanoid(), text: 'An', categories: ['Article'] }, { id: nanoid(), text: 'An', categories: ['Article'] },
  { id: nanoid(), text: 'An', categories: ['Article'] }, { id: nanoid(), text: 'An', categories: ['Article'] },
  { id: nanoid(), text: 'The', categories: ['Article'] }, { id: nanoid(), text: 'The', categories: ['Article'] },
  { id: nanoid(), text: 'The', categories: ['Article'] }, { id: nanoid(), text: 'The', categories: ['Article'] },
  { id: nanoid(), text: 'The', categories: ['Article'] }, { id: nanoid(), text: 'The', categories: ['Article'] },
  { id: nanoid(), text: 'The', categories: ['Article'] }, { id: nanoid(), text: 'The', categories: ['Article'] },

  // Prepositions - many already covered
  { id: nanoid(), text: 'In', categories: ['Preposition', 'Adverb', 'Adjective', 'Noun'] }, { id: nanoid(), text: 'In', categories: ['Preposition', 'Adverb', 'Adjective', 'Noun'] },
  { id: nanoid(), text: 'On', categories: ['Preposition', 'Adverb', 'Adjective'] }, { id: nanoid(), text: 'On', categories: ['Preposition', 'Adverb', 'Adjective'] },
  { id: nanoid(), text: 'At', categories: ['Preposition'] }, { id: nanoid(), text: 'At', categories: ['Preposition'] },
  { id: nanoid(), text: 'With', categories: ['Preposition'] }, { id: nanoid(), text: 'With', categories: ['Preposition'] },
  { id: nanoid(), text: 'By', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'By', categories: ['Preposition', 'Adverb'] },
  { id: nanoid(), text: 'For', categories: ['Preposition', 'Conjunction'] }, { id: nanoid(), text: 'For', categories: ['Preposition', 'Conjunction'] }, 
  { id: nanoid(), text: 'From', categories: ['Preposition'] }, { id: nanoid(), text: 'From', categories: ['Preposition'] },
  { id: nanoid(), text: 'To', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'To', categories: ['Preposition', 'Adverb'] },
  { id: nanoid(), text: 'Up', categories: ['Preposition', 'Adverb', 'Adjective', 'Noun', 'Verb'] }, { id: nanoid(), text: 'Down', categories: ['Preposition', 'Adverb', 'Adjective', 'Noun', 'Verb'] },
  { id: nanoid(), text: 'About', categories: ['Preposition', 'Adverb'] }, 
  { id: nanoid(), text: 'Above', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'After', categories: ['Preposition', 'Adverb', 'Conjunction', 'Adjective'] }, 
  { id: nanoid(), text: 'Along', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'Around', categories: ['Preposition', 'Adverb'] },
  { id: nanoid(), text: 'Before', categories: ['Preposition', 'Adverb', 'Conjunction'] }, { id: nanoid(), text: 'Behind', categories: ['Preposition', 'Adverb', 'Noun'] }, 
  { id: nanoid(), text: 'Below', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'Beside', categories: ['Preposition'] },
  { id: nanoid(), text: 'Between', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'During', categories: ['Preposition'] },
  { id: nanoid(), text: 'Into', categories: ['Preposition'] }, 
  { id: nanoid(), text: 'Onto', categories: ['Preposition'] }, { id: nanoid(), text: 'Out', categories: ['Preposition', 'Adverb', 'Adjective', 'Verb', 'Noun'] },
  { id: nanoid(), text: 'Past', categories: ['Preposition', 'Adjective', 'Adverb', 'Noun'] }, { id: nanoid(), text: 'Since', categories: ['Preposition', 'Adverb', 'Conjunction'] }, 
  { id: nanoid(), text: 'Through', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'Toward', categories: ['Preposition'] },
  { id: nanoid(), text: 'Until', categories: ['Preposition', 'Conjunction'] }, { id: nanoid(), text: 'Upon', categories: ['Preposition'] }, 
  { id: nanoid(), text: 'Across', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'Against', categories: ['Preposition'] },
  { id: nanoid(), text: 'Among', categories: ['Preposition'] }, { id: nanoid(), text: 'Beyond', categories: ['Preposition', 'Adverb'] },
  { id: nanoid(), text: 'Concerning', categories: ['Preposition'] }, { id: nanoid(), text: 'Despite', categories: ['Preposition'] },
  { id: nanoid(), text: 'Except', categories: ['Preposition', 'Conjunction', 'Verb'] }, { id: nanoid(), text: 'Inside', categories: ['Preposition', 'Adverb', 'Noun', 'Adjective'] },
  { id: nanoid(), text: 'Near', categories: ['Preposition', 'Adverb', 'Adjective', 'Verb'] }, { id: nanoid(), text: 'Of', categories: ['Preposition'] },
  { id: nanoid(), text: 'Off', categories: ['Preposition', 'Adverb', 'Adjective'] }, { id: nanoid(), text: 'Outside', categories: ['Preposition', 'Adverb', 'Noun', 'Adjective'] },
  { id: nanoid(), text: 'Over', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'Regarding', categories: ['Preposition'] },
  { id: nanoid(), text: 'Underneath', categories: ['Preposition', 'Adverb'] }, { id: nanoid(), text: 'Within', categories: ['Preposition', 'Adverb'] },
  { id: nanoid(), text: 'Without', categories: ['Preposition', 'Adverb'] },


  // Conjunctions - many already covered
  { id: nanoid(), text: 'And', categories: ['Conjunction'] }, { id: nanoid(), text: 'And', categories: ['Conjunction'] },
  { id: nanoid(), text: 'And', categories: ['Conjunction'] }, { id: nanoid(), text: 'And', categories: ['Conjunction'] },
  { id: nanoid(), text: 'And', categories: ['Conjunction'] }, { id: nanoid(), text: 'And', categories: ['Conjunction'] },
  { id: nanoid(), text: 'But', categories: ['Conjunction', 'Preposition', 'Adverb', 'Noun'] }, { id: nanoid(), text: 'But', categories: ['Conjunction', 'Preposition', 'Adverb', 'Noun'] },
  { id: nanoid(), text: 'But', categories: ['Conjunction', 'Preposition', 'Adverb', 'Noun'] }, { id: nanoid(), text: 'But', categories: ['Conjunction', 'Preposition', 'Adverb', 'Noun'] },
  { id: nanoid(), text: 'Or', categories: ['Conjunction'] }, { id: nanoid(), text: 'Or', categories: ['Conjunction'] },
  { id: nanoid(), text: 'Or', categories: ['Conjunction'] }, { id: nanoid(), text: 'Or', categories: ['Conjunction'] },
  { id: nanoid(), text: 'Nor', categories: ['Conjunction'] },
  { id: nanoid(), text: 'Although', categories: ['Conjunction'] }, 
  { id: nanoid(), text: 'As', categories: ['Conjunction', 'Adverb', 'Preposition'] }, { id: nanoid(), text: 'Because', categories: ['Conjunction'] },
  { id: nanoid(), text: 'If', categories: ['Conjunction', 'Noun'] }, 
  { id: nanoid(), text: 'Than', categories: ['Conjunction', 'Preposition'] },
  { id: nanoid(), text: 'Though', categories: ['Conjunction', 'Adverb'] }, { id: nanoid(), text: 'Unless', categories: ['Conjunction'] }, 
  { id: nanoid(), text: 'While', categories: ['Conjunction', 'Noun', 'Verb'] }, 
  { id: nanoid(), text: 'Therefore', categories: ['Adverb'] }, 
  { id: nanoid(), text: 'Moreover', categories: ['Adverb'] },  
  { id: nanoid(), text: 'Nevertheless', categories: ['Adverb'] }, 
  { id: nanoid(), text: 'So', categories: ['Conjunction', 'Adverb'] }, { id: nanoid(), text: 'Yet', categories: ['Conjunction', 'Adverb'] },
  { id: nanoid(), text: 'For', categories: ['Conjunction', 'Preposition'] }, // Coordinating conjunction
  { id: nanoid(), text: 'After', categories: ['Conjunction', 'Preposition', 'Adverb', 'Adjective'] }, // Subordinating
  { id: nanoid(), text: 'Before', categories: ['Conjunction', 'Preposition', 'Adverb'] }, // Subordinating
  { id: nanoid(), text: 'Since', categories: ['Conjunction', 'Preposition', 'Adverb'] }, // Subordinating
  { id: nanoid(), text: 'Until', categories: ['Conjunction', 'Preposition'] }, // Subordinating
  { id: nanoid(), text: 'When', categories: ['Conjunction', 'Adverb', 'Pronoun'] }, // Subordinating
  { id: nanoid(), text: 'Whenever', categories: ['Conjunction'] },
  { id: nanoid(), text: 'Where', categories: ['Conjunction', 'Adverb', 'Pronoun'] }, // Subordinating
  { id: nanoid(), text: 'Wherever', categories: ['Conjunction'] },
  { id: nanoid(), text: 'Whether', categories: ['Conjunction'] },
  { id: nanoid(), text: 'Once', categories: ['Conjunction', 'Adverb', 'Noun'] }, // Subordinating
  { id: nanoid(), text: 'Than', categories: ['Conjunction', 'Preposition'] }, // Subordinating
  { id: nanoid(), text: 'That', categories: ['Conjunction', 'Pronoun', 'Adjective', 'Adverb'] }, // Subordinating
  { id: nanoid(), text: 'Though', categories: ['Conjunction', 'Adverb'] }, // Subordinating
  { id: nanoid(), text: 'Unless', categories: ['Conjunction'] }, // Subordinating
  { id: nanoid(), text: 'Until', categories: ['Conjunction', 'Preposition'] }, // Subordinating
  { id: nanoid(), text: 'As if', categories: ['Conjunction'] }, // Multi-word, handle as single unit if possible, or use logic
  { id: nanoid(), text: 'As long as', categories: ['Conjunction'] },
  { id: nanoid(), text: 'As though', categories: ['Conjunction'] },
  { id: nanoid(), text: 'In order that', categories: ['Conjunction'] },
  { id: nanoid(), text: 'Provided that', categories: ['Conjunction'] },
  { id: nanoid(), text: 'So that', categories: ['Conjunction'] },
];

export const SENTENCE_PATTERNS: SentencePattern[] = [
  // Very Simple Patterns (can act as clauses)
  { name: "Noun", structure: [['Noun']]},
  { name: "Pronoun-Verb", structure: [['Pronoun', 'Verb']] }, 
  { name: "Article-Noun-Verb", structure: [['Article', 'Noun', 'Verb']] }, 
  { name: "Noun-Verb", structure: [['Noun', 'Verb']] }, 
  { name: "Verb-Noun", structure: [['Verb', 'Noun']] }, 
  { name: "Verb-Pronoun", structure: [['Verb', 'Pronoun']] }, 
  { name: "Verb-Article-Noun", structure: [['Verb', 'Article', 'Noun']]}, 
  { name: "Article-Noun", structure: [['Article', 'Noun']]},
  { name: "Adjective-Noun", structure: [['Adjective', 'Noun']] }, 
  { name: "Article-Adjective-Noun", structure: [['Article', 'Adjective', 'Noun']] }, 

  // Basic S-V-O
  { name: "Pronoun-Verb-Noun", structure: [['Pronoun', 'Verb', 'Noun']] }, 
  { name: "Pronoun-Verb-Pronoun", structure: [['Pronoun', 'Verb', 'Pronoun']] }, 
  { name: "Article-Noun-Verb-Noun", structure: [['Article', 'Noun', 'Verb', 'Noun']] }, 
  { name: "Noun-Verb-Noun", structure: [['Noun', 'Verb', 'Noun']] }, 
  { name: "Pronoun-Verb-Article-Noun", structure: [['Pronoun', 'Verb', 'Article', 'Noun']] }, 
  { name: "Noun-Verb-Article-Noun", structure: [['Noun', 'Verb', 'Article', 'Noun']] },
  
  // Patterns with Adjectives
  { name: "Pronoun-Verb-Adjective", structure: [['Pronoun', 'Verb', 'Adjective']] }, 
  { name: "Noun-Verb-Adjective", structure: [['Noun', 'Verb', 'Adjective']] }, 
  { name: "Article-Noun-Verb-Adjective", structure: [['Article', 'Noun', 'Verb', 'Adjective']] }, 
  { name: "Adjective-Noun-Verb", structure: [['Adjective', 'Noun', 'Verb']] }, 
  { name: "Article-Adjective-Noun-Verb", structure: [['Article', 'Adjective', 'Noun', 'Verb']] }, 
  { name: "Pronoun-Verb-Adjective-Noun", structure: [['Pronoun', 'Verb', 'Adjective', 'Noun']] }, 
  { name: "Article-Noun-Verb-Adjective-Noun", structure: [['Article', 'Noun', 'Verb', 'Adjective', 'Noun']] },
  { name: "Noun-Verb-Noun-Adjective", structure: [['Noun', 'Verb', 'Noun', 'Adjective']] },
  { name: "Pronoun-Verb-Noun-Adjective", structure: [['Pronoun', 'Verb', 'Noun', 'Adjective']] },
  { name: "Article-Noun-Verb-Article-Adjective-Noun", structure: [['Article', 'Noun', 'Verb', 'Article', 'Adjective', 'Noun']]},

  // Patterns with Adverbs
  { name: "Pronoun-Verb-Adverb", structure: [['Pronoun', 'Verb', 'Adverb']] }, 
  { name: "Noun-Verb-Adverb", structure: [['Noun', 'Verb', 'Adverb']] }, 
  { name: "Article-Noun-Verb-Adverb", structure: [['Article', 'Noun', 'Verb', 'Adverb']] }, 
  { name: "Pronoun-Adverb-Verb", structure: [['Pronoun', 'Adverb', 'Verb']] }, 
  { name: "Noun-Adverb-Verb", structure: [['Noun', 'Adverb', 'Verb']] }, 
  { name: "Adverb-Verb", structure: [['Adverb', 'Verb']] }, 
  { name: "Article-Adjective-Noun-Verb-Adverb", structure: [['Article', 'Adjective', 'Noun', 'Verb', 'Adverb']] }, 
  { name: "Pronoun-Verb-Noun-Adverb", structure: [['Pronoun', 'Verb', 'Noun', 'Adverb']]}, 
  { name: "Article-Adverb-Adjective-Noun", structure: [['Article', 'Adverb', 'Adjective', 'Noun']] }, 
  { name: "Adverb-Adjective-Noun", structure: [['Adverb', 'Adjective', 'Noun']] }, 
  { name: "Adverb-Verb-Noun", structure: [['Adverb', 'Verb', 'Noun']]}, 
  { name: "Adverb-Verb-Article-Noun", structure: [['Adverb', 'Verb', 'Article', 'Noun']]}, 
  { name: "Adverb-Verb-Adjective", structure: [['Adverb', 'Verb', 'Adjective']]}, 
  { name: "Adverb-Verb-Adverb", structure: [['Adverb', 'Verb', 'Adverb']]},
  { name: "Verb-Adverb", structure: [['Verb', 'Adverb']]},
  { name: "Noun-Verb-Adverb-Noun", structure: [['Noun', 'Verb', 'Adverb', 'Noun']]},
  { name: "Pronoun-Verb-Adverb-Pronoun", structure: [['Pronoun', 'Verb', 'Adverb', 'Pronoun']]},

  // Patterns with Prepositions
  { name: "Pronoun-Verb-Preposition-Article-Noun", structure: [['Pronoun', 'Verb', 'Preposition', 'Article', 'Noun']] }, 
  { name: "Noun-Verb-Preposition-Noun", structure: [['Noun', 'Verb', 'Preposition', 'Noun']] }, 
  { name: "Article-Noun-Verb-Preposition-Article-Noun", structure: [['Article', 'Noun', 'Verb', 'Preposition', 'Article', 'Noun']] }, 
  { name: "Verb-Preposition-Noun", structure: [['Verb', 'Preposition', 'Noun']]}, 
  { name: "Verb-Preposition-Article-Noun", structure: [['Verb', 'Preposition', 'Article', 'Noun']]}, 
  { name: "Noun-Preposition-Noun", structure: [['Noun', 'Preposition', 'Noun']]}, 
  { name: "Article-Noun-Preposition-Article-Noun", structure: [['Article', 'Noun', 'Preposition', 'Article', 'Noun']]}, 
  { name: "Pronoun-Verb-Adverb-Preposition-Article-Noun", structure: [['Pronoun', 'Verb', 'Adverb', 'Preposition', 'Article', 'Noun']]}, 
  { name: "Pronoun-Verb-Noun-Preposition-Article-Noun", structure: [['Pronoun', 'Verb', 'Noun', 'Preposition', 'Article', 'Noun']] }, 
  { name: "Article-Noun-Verb-Noun-Preposition-Article-Noun", structure: [['Article', 'Noun', 'Verb', 'Noun', 'Preposition', 'Article', 'Noun']] }, 
  { name: "Verb-Noun-Preposition-Noun", structure: [['Verb', 'Noun', 'Preposition', 'Noun']]}, 
  { name: "Noun-Preposition-Article-Noun-Verb", structure: [['Noun', 'Preposition', 'Article', 'Noun', 'Verb']]}, 
  { name: "Pronoun-Verb-Preposition-Pronoun", structure: [['Pronoun', 'Verb', 'Preposition', 'Pronoun']]},
  { name: "Preposition-Noun", structure: [['Preposition', 'Noun']]}, 
  { name: "Preposition-Article-Noun", structure: [['Preposition', 'Article', 'Noun']]}, 
  { name: "Preposition-Adjective-Noun", structure: [['Preposition', 'Adjective', 'Noun']]}, 
  { name: "Noun-Verb-Preposition-Adjective-Noun", structure: [['Noun', 'Verb', 'Preposition', 'Adjective', 'Noun']]},
  { name: "Pronoun-Verb-Noun-Preposition-Adjective-Noun", structure: [['Pronoun', 'Verb', 'Noun', 'Preposition', 'Adjective', 'Noun']]},
  { name: "Article-Noun-Verb-Preposition-Pronoun", structure: [['Article', 'Noun', 'Verb', 'Preposition', 'Pronoun']]},

  // Patterns with Conjunctions (these are for direct matching of a sequence that includes a conjunction,
  // the new logic will handle clause + conjunction + clause separately if no direct match)
  { name: "Noun-Verb-Conjunction-Noun-Verb", structure: [['Noun', 'Verb', 'Conjunction', 'Noun', 'Verb']] }, 
  { name: "Pronoun-Verb-Conjunction-Pronoun-Verb", structure: [['Pronoun', 'Verb', 'Conjunction', 'Pronoun', 'Verb']] }, 
  { name: "Noun-Conjunction-Noun-Verb", structure: [['Noun', 'Conjunction', 'Noun', 'Verb']]}, 
  { name: "Verb-Conjunction-Verb", structure: [['Verb', 'Conjunction', 'Verb']]}, 
  { name: "Adjective-Conjunction-Adjective", structure: [['Adjective', 'Conjunction', 'Adjective']]}, 
  { name: "Noun-Verb-Noun-Conjunction-Verb-Noun", structure: [['Noun', 'Verb', 'Noun', 'Conjunction', 'Verb', 'Noun']] }, 
  { name: "Pronoun-Verb-Adjective-Conjunction-Verb-Adjective", structure: [['Pronoun', 'Verb', 'Adjective', 'Conjunction', 'Verb', 'Adjective']] }, 
  { name: "Article-Noun-Verb-Conjunction-Article-Noun-Verb", structure: [['Article', 'Noun', 'Verb', 'Conjunction', 'Article', 'Noun', 'Verb']] }, 
  
  // Specific "to be" verb patterns (Is, Are, Was, Were, etc. are just 'Verb' category)
  { name: "Article-Noun-Is-Noun", structure: [['Article', 'Noun', 'Verb', 'Noun']] }, 
  { name: "Pronoun-Is-Noun", structure: [['Pronoun', 'Verb', 'Noun']] }, 
  { name: "Pronoun-Is-Article-Noun", structure: [['Pronoun', 'Verb', 'Article', 'Noun']] }, 
  { name: "Adjective-Noun-Is-Adjective", structure: [['Adjective', 'Noun', 'Verb', 'Adjective']]},
  { name: "Noun-Is-Adjective", structure: [['Noun', 'Verb', 'Adjective']]}, // same as Noun-Verb-Adjective
  
  // More varied structures
  { name: "Pronoun-Verb-Article-Adjective-Noun", structure: [['Pronoun', 'Verb', 'Article', 'Adjective', 'Noun']]}, 
  { name: "Noun-Verb-Article-Adjective-Noun", structure: [['Noun', 'Verb', 'Article', 'Adjective', 'Noun']]}, 
  { name: "Article-Adjective-Noun-Verb-Article-Noun", structure: [['Article', 'Adjective', 'Noun', 'Verb', 'Article', 'Noun']]}, 
  { name: "Article-Noun-Adverb-Verb-Adjective", structure: [['Article', 'Noun', 'Adverb', 'Verb', 'Adjective']]}, 
  { name: "Pronoun-Adverb-Verb-Article-Noun", structure: [['Pronoun', 'Adverb', 'Verb', 'Article', 'Noun']]}, 
  { name: "Noun-Verb-Pronoun-Adverb", structure: [['Noun', 'Verb', 'Pronoun', 'Adverb']]}, 
  { name: "Verb-Noun-Preposition-Article-Noun", structure: [['Verb', 'Noun', 'Preposition', 'Article', 'Noun']]}, 
  { name: "Article-Noun-Verb-Adjective-Preposition-Noun", structure: [['Article', 'Noun', 'Verb', 'Adjective', 'Preposition', 'Noun']]}, 
  { name: "Pronoun-Verb-Adverb-Adjective", structure: [['Pronoun', 'Verb', 'Adverb', 'Adjective']]}, 
  { name: "Noun-Verb-Adverb-Adjective", structure: [['Noun', 'Verb', 'Adverb', 'Adjective']]},
  { name: "Pronoun-Verb-Adjective-Preposition-Noun", structure: [['Pronoun', 'Verb', 'Adjective', 'Preposition', 'Noun']]},
  { name: "Noun-Adverb-Verb-Noun", structure: [['Noun', 'Adverb', 'Verb', 'Noun']]},
  { name: "Adverb-Pronoun-Verb-Noun", structure: [['Adverb', 'Pronoun', 'Verb', 'Noun']]},
  { name: "Article-Noun-Verb-Noun-Adverb", structure: [['Article', 'Noun', 'Verb', 'Noun', 'Adverb']]},
  
  // Longer and more complex combinations
  { name: "Article-Adjective-Noun-Verb-Article-Adjective-Noun", structure: [['Article', 'Adjective', 'Noun', 'Verb', 'Article', 'Adjective', 'Noun']]}, 
  { name: "Pronoun-Verb-Noun-Preposition-Article-Adjective-Noun", structure: [['Pronoun', 'Verb', 'Noun', 'Preposition', 'Article', 'Adjective', 'Noun']]}, 
  { name: "Article-Noun-Verb-Noun-Conjunction-Noun-Verb-Noun", structure: [['Article', 'Noun', 'Verb', 'Noun', 'Conjunction', 'Noun', 'Verb', 'Noun']] }, 
  { name: "Pronoun-Verb-Adjective-Noun-Preposition-Article-Noun", structure: [['Pronoun', 'Verb', 'Adjective', 'Noun', 'Preposition', 'Article', 'Noun']] }, 
  { name: "Article-Noun-Verb-Adverb-Preposition-Article-Adjective-Noun", structure: [['Article', 'Noun', 'Verb', 'Adverb', 'Preposition', 'Article', 'Adjective', 'Noun']] }, 
  { name: "Pronoun-Verb-Conjunction-Verb-Article-Adjective-Noun", structure: [['Pronoun', 'Verb', 'Conjunction', 'Verb', 'Article', 'Adjective', 'Noun']] }, 
  { name: "Noun-Adverb-Verb-Adjective-Conjunction-Noun-Verb-Adverb", structure: [['Noun', 'Adverb', 'Verb', 'Adjective', 'Conjunction', 'Noun', 'Verb', 'Adverb']] }, 
  { name: "Pronoun-Verb-Article-Noun-Preposition-Article-Noun-Conjunction-Verb-More", structure: [['Pronoun', 'Verb', 'Article', 'Noun', 'Preposition', 'Article', 'Noun', 'Conjunction', 'Verb', 'Adverb']]}, 
  { name: "Adverb-Verb-Article-Adjective-Noun", structure: [['Adverb', 'Verb', 'Article', 'Adjective', 'Noun']]}, 
  { name: "Article-Adjective-Noun-Verb-Adjective-Noun", structure: [['Article', 'Adjective', 'Noun', 'Verb', 'Adjective', 'Noun']]},
  { name: "Article-Noun-Verb-Noun-Preposition-Adjective-Noun", structure: [['Article', 'Noun', 'Verb', 'Noun', 'Preposition', 'Adjective', 'Noun']]}, 
  { name: "Pronoun-Verb-Adjective-Noun-Conjunction-Pronoun-Verb-Adjective-Noun", structure: [['Pronoun', 'Verb', 'Adjective', 'Noun', 'Conjunction', 'Pronoun', 'Verb', 'Adjective', 'Noun']]}, 
  { name: "Noun-Verb-Preposition-Article-Noun-Adverb", structure: [['Noun', 'Verb', 'Preposition', 'Article', 'Noun', 'Adverb']]}, 
  { name: "Pronoun-Verb-Noun-Preposition-Pronoun-Adverb", structure: [['Pronoun', 'Verb', 'Noun', 'Preposition', 'Pronoun', 'Adverb']]}, 
  { name: "Article-Adjective-Noun-Verb-Pronoun-Adverb", structure: [['Article', 'Adjective', 'Noun', 'Verb', 'Pronoun', 'Adverb']]}, 
  { name: "Noun-Verb-Article-Adjective-Noun-Preposition-Noun", structure: [['Noun', 'Verb', 'Article', 'Adjective', 'Noun', 'Preposition', 'Noun']]}, 
  { name: "Adverb-Pronoun-Verb-Article-Noun-Conjunction-Verb-Adverb", structure: [['Adverb', 'Pronoun', 'Verb', 'Article', 'Noun', 'Conjunction', 'Verb', 'Adverb']]}, 
  { name: "Verb-Article-Noun-Preposition-Article-Adjective-Noun", structure: [['Verb', 'Article', 'Noun', 'Preposition', 'Article', 'Adjective', 'Noun']]}, 
  { name: "Pronoun-AuxVerb-Adverb-Verb-Noun", structure: [['Pronoun', 'Verb', 'Adverb', 'Verb', 'Noun']]}, // AuxVerb is just 'Verb'                                                                                                  
  { name: "Article-Noun-Preposition-Article-Noun-Verb-Adverb", structure: [['Article', 'Noun', 'Preposition', 'Article', 'Noun', 'Verb', 'Adverb']]}, 
  { name: "Conjunction-Pronoun-Verb-Noun-Pronoun-Verb-Adjective", structure: [['Conjunction', 'Pronoun', 'Verb', 'Noun', 'Pronoun', 'Verb', 'Adjective']]}, 
  { name: "Noun-Verb-Adjective-Preposition-Article-Noun-Adverb", structure: [['Noun', 'Verb', 'Adjective', 'Preposition', 'Article', 'Noun', 'Adverb']]},
  { name: "Adjective-Noun-Verb-Preposition-Article-Noun", structure: [['Adjective', 'Noun', 'Verb', 'Preposition', 'Article', 'Noun']]},
  { name: "Noun-Verb-Preposition-Adjective-Noun-Adverb", structure: [['Noun', 'Verb', 'Preposition', 'Adjective', 'Noun', 'Adverb']]},
  { name: "Pronoun-Verb-Adverb-Preposition-Adjective-Noun", structure: [['Pronoun', 'Verb', 'Adverb', 'Preposition', 'Adjective', 'Noun']]},

  // Question Forms (simple examples, auxiliary verbs are just 'Verb')
  { name: "Verb-Pronoun-Verb-Noun", structure: [['Verb', 'Pronoun', 'Verb', 'Noun']]}, 
  { name: "Verb-Article-Noun-Verb-Adjective", structure: [['Verb', 'Article', 'Noun', 'Verb', 'Adjective']]}, 
  { name: "Verb-Noun-Verb-Preposition-Noun", structure: [['Verb', 'Noun', 'Verb', 'Preposition', 'Noun']]}, 
  { name: "Pronoun(Wh)-Verb-Pronoun-Verb", structure: [['Pronoun', 'Verb', 'Pronoun', 'Verb']]}, // Who Did You See
  { name: "Verb-Noun-Verb-Adverb", structure: [['Verb', 'Noun', 'Verb', 'Adverb']]}, // Did Dogs Run Quickly
  { name: "Verb-Pronoun-Adjective", structure: [['Verb', 'Pronoun', 'Adjective']]}, // Is He Happy

  // More Fragments that can act as clauses
  { name: "Adverb-Adjective", structure: [['Adverb', 'Adjective']]}, 
  { name: "Adjective-Noun-Preposition-Noun", structure: [['Adjective', 'Noun', 'Preposition', 'Noun']]}, 
  { name: "Article-Adjective-Noun-Preposition-Article-Noun", structure: [['Article', 'Adjective', 'Noun', 'Preposition', 'Article', 'Noun']]}, 

  // Patterns with multiple adjectives or adverbs
  { name: "Article-Adjective-Adjective-Noun", structure: [['Article', 'Adjective', 'Adjective', 'Noun']]}, 
  { name: "Noun-Verb-Adverb-Adverb", structure: [['Noun', 'Verb', 'Adverb', 'Adverb']]}, 
  { name: "Pronoun-Verb-Adjective-Adjective", structure: [['Pronoun', 'Verb', 'Adjective', 'Adjective']]}, 
  { name: "Adverb-Adverb-Verb", structure: [['Adverb', 'Adverb', 'Verb']]}, 
  { name: "Adverb-Adjective-Noun-Verb", structure: [['Adverb', 'Adjective', 'Noun', 'Verb']]},
  { name: "Noun-Verb-Adjective-Adjective", structure: [['Noun', 'Verb', 'Adjective', 'Adjective']]},

  // Patterns emphasizing specific conjunction uses (for direct matching, otherwise split logic handles it)
  { name: "Pronoun-Verb-Noun-Conjunction-Pronoun-Verb-Noun-Adverb", structure: [['Pronoun', 'Verb', 'Noun', 'Conjunction', 'Pronoun', 'Verb', 'Noun', 'Adverb']]}, 
  { name: "If-Pronoun-Verb-Then-Pronoun-Verb", structure: [['Conjunction', 'Pronoun', 'Verb', 'Conjunction', 'Pronoun', 'Verb']]},
  { name: "Noun-Verb-Adjective-Because-Noun-Verb-Adjective", structure: [['Noun', 'Verb', 'Adjective', 'Conjunction', 'Noun', 'Verb', 'Adjective']]},
  { name: "Article-Noun-Verb-Adverb-Preposition-Article-Adjective-Noun-Conjunction-Verb-Adverb", structure: [['Article', 'Noun', 'Verb', 'Adverb', 'Preposition', 'Article', 'Adjective', 'Noun', 'Conjunction', 'Verb', 'Adverb']]}, 
  { name: "Pronoun-Verb-Article-Noun-While-Pronoun-Verb-Article-Noun", structure: [['Pronoun', 'Verb', 'Article', 'Noun', 'Conjunction', 'Pronoun', 'Verb', 'Article', 'Noun']]}, 
  { name: "Although-Noun-Verb-Adjective-Pronoun-Still-Verb-Noun", structure: [['Conjunction', 'Noun', 'Verb', 'Adjective', 'Pronoun', 'Adverb', 'Verb', 'Noun']]}, 
  { name: "Noun-Conjunction-Noun", structure: [['Noun', 'Conjunction', 'Noun']]}, // Apples and Oranges
  { name: "Adjective-Conjunction-Adjective", structure: [['Adjective', 'Conjunction', 'Adjective']]}, // Big and Tall
  { name: "Verb-Conjunction-Verb", structure: [['Verb', 'Conjunction', 'Verb']]}, // Run and Jump
];


export const SAME_LETTER_GROUP_MIN_LENGTH = 3;
